In [3]:
import numpy as np

In [11]:
y = [0,1,2,2,1]


In [6]:
t = np.zeros((len(y), 3))
t

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:

t[0, y[0]] = 1
t

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
for i in range(len(y)):
    t[i, y[i]] = 1

t

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3)[y]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])